#server.port=5555
#
#
#resilience4j.circuitbreaker.configs.default.slidingWindowSize=100
#resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=10
#resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000
#resilience4j.circuitbreaker.configs.default.failureRateThreshold=60
#resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10
#resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
#resilience4j.circuitbreaker.instances.testingA.baseConfig=default
#resilience4j.circuitbreaker.configs.default.recordExceptions=org.springframework.web.client.ResourceAccessException
#


server:
  port: 5555

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
    instances:
      ratingService:
        baseConfig: default